# @package _global_
defaults:
  - /model/base@planner_model
  - /model/base@reporter_model
  - /agents/simple/mysql_db_worker@workers.DBSchemaAgent
  - /agents/simple/py_d_clean@workers.PyDAgent
  - /agents/simple/analysis_agent@workers.InsightAgent
  - _self_

type: orchestra

planner_config:
  examples_path: examples/mysql_analytics/planner_examples_data.json

reporter_config:
  template_path: ${oc.env:UTU_REPORT_TEMPLATE,examples/data_analysis/web_reporter_sp.j2}

workers_info:
  - name: DBSchemaAgent
    desc: Connects to MySQL, maps schema and relationships, drafts ER (Mermaid), and hard-gates downstream via user confirmation.
    strengths: INFORMATION_SCHEMA discovery, PK/FK inference, semantic table search, ER generation
    weaknesses: Requires mysql CLI and read-only creds; heavy introspection needs caution
  - name: PyDAgent
    desc: Reads from DB tools (exec_sql/export_query_tsv), runs Python EDA/metrics, and renders charts inline via Mermaid; no local image files.
    strengths: pandas/numpy workflows; safe incremental queries; inline Mermaid outputs for Web UI
    weaknesses: Avoids heavy packages and Python direct DB connections unless approved
  - name: InsightAgent
    desc: Synthesizes metrics and artifacts into a business report with actionable recommendations.
    strengths: Structure, clarity, commercial insights; merges trajectory into a coherent report
    weaknesses: Relies on upstream artifacts being accurate and sufficiently rich

